FROM gradescope/autograder-base:latest

# Install dependencies
RUN apt-get update && apt-get install -y \
    openssh-client \
    curl \
    jq

# Add SSH private key
COPY id_ed25519 /root/.ssh/id_ed25519
RUN chmod 600 /root/.ssh/id_ed25519

# Disable strict host key checking
RUN echo -e "Host *\n    StrictHostKeyChecking no\n" >> /root/.ssh/config

# Add run_autograder script
COPY run_autograder /autograder/source/run_autograder
RUN chmod +x /autograder/source/run_autograder
