apiVersion: batch/v1
kind: Job
metadata:
    name: test-py-kubernetes
    spec:
        template:
              spec:
                      containers:
                              - name: python
                                        image: ajayrr/test-py-kubernetes:arm64
                                                restartPolicy: Never
                                                    backoffLimit: 2
